/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;
import Conexion.datosP;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
/**
 *
 * @author Klope
 */
public class JF_AgregarCliente extends javax.swing.JFrame {
PreparedStatement pst;
ResultSet rs;
datosP con= new datosP();
      Connection c=con.conexion();
    /**
     * Creates new form cliente
     */
    public JF_AgregarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsuarioVentas2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtapellido1 = new javax.swing.JTextField();
        txtapellido2 = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        btnagregar = new javax.swing.JButton();
        btneditar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtbusqueda = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(181, 62, 12));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jButton1.setText("INICIO");
        jButton1.setBorder(null);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 166, 37));

        jButton2.setBackground(new java.awt.Color(181, 62, 12));
        jButton2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jButton2.setText("FACTURACION");
        jButton2.setBorder(null);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 166, 39));

        jButton3.setBackground(new java.awt.Color(181, 62, 12));
        jButton3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jButton3.setText("INVENTARIOS");
        jButton3.setBorder(null);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 166, 34));

        jButton4.setBackground(new java.awt.Color(181, 62, 12));
        jButton4.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jButton4.setText("HISTORIAL DE VENTAS");
        jButton4.setBorder(null);
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 166, 35));

        jButton5.setBackground(new java.awt.Color(181, 62, 12));
        jButton5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 12)); // NOI18N
        jButton5.setText("SALIR");
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 166, 34));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inventory.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 31, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/factura.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 42, 54));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comprar.png"))); // NOI18N
        jLabel3.setText("jLabel1");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 42, 48));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/oficina-en-casa.png"))); // NOI18N
        jLabel4.setText("jLabel1");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 42, 43));

        txtUsuarioVentas2.setEditable(false);
        txtUsuarioVentas2.setBackground(new java.awt.Color(245, 245, 245));
        txtUsuarioVentas2.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        txtUsuarioVentas2.setText("      ");
        txtUsuarioVentas2.setBorder(null);
        txtUsuarioVentas2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioVentas2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuarioVentas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 120, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 890));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Agregar Cliente");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(471, 471, 471)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(705, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 0, 1400, 50));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel6.setText("Cédula");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(64, 26, 38, 15);

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel7.setText("Nombre");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(64, 85, 44, 15);

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel8.setText("Primer apellido");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(64, 143, 88, 15);

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel9.setText("Segundo apellido");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(64, 193, 97, 15);

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel10.setText("E-mail");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(64, 241, 35, 15);
        jPanel3.add(txtcedula);
        txtcedula.setBounds(261, 24, 246, 30);
        jPanel3.add(txtnombre);
        txtnombre.setBounds(261, 83, 246, 30);

        txtapellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellido1ActionPerformed(evt);
            }
        });
        jPanel3.add(txtapellido1);
        txtapellido1.setBounds(261, 141, 246, 30);
        jPanel3.add(txtapellido2);
        txtapellido2.setBounds(261, 191, 246, 30);
        jPanel3.add(txtemail);
        txtemail.setBounds(261, 239, 246, 30);

        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });
        jPanel3.add(btnagregar);
        btnagregar.setBounds(580, 30, 125, 36);

        btneditar.setText("Editar");
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });
        jPanel3.add(btneditar);
        btneditar.setBounds(580, 90, 125, 36);

        btneliminar.setText("Eliminar");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btneliminar);
        btneliminar.setBounds(580, 150, 125, 36);

        jLabel11.setText("ID");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(530, 270, 30, 14);
        jPanel3.add(txtbusqueda);
        txtbusqueda.setBounds(580, 260, 130, 30);

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jPanel3.add(btnbuscar);
        btnbuscar.setBounds(580, 210, 125, 36);

        jPanel4.add(jPanel3);
        jPanel3.setBounds(160, 230, 760, 300);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 1360, 840));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtapellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellido1ActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
       
        
        // Sql query para el ingreso de datos a la BD
        
      
      try{
          PreparedStatement pst = c.prepareStatement("INSERT INTO registro_cliente(Cédula,"
                    + "Nombre,PrimerApellido,SegundoApellido,CorreoElectronico) VALUES (?,?,?,?,?)");

            pst.setString(1, txtcedula.getText());
            pst.setString(2, txtnombre.getText());
            pst.setString(3, txtapellido1.getText());
            pst.setString(4, txtapellido2.getText());
            pst.setString(5, txtemail.getText());

            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Cliente guardado con éxito");

        
            
            con.Desconectar();
      }catch(Exception e){
          JOptionPane.showMessageDialog(null,"Error al agregar el Cliente: "+e);
      }
        
        
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
       
        try {
            //CONSULTA PARA LA MODIFICACIÓN
            pst = con.conexion().prepareStatement("UPDATE registro_cliente SET Cédula=?,Nombre=?,PrimerApellido=?,SegundoApellido=?,CorreoElectronico=? WHERE Id_Cliente=? ");
            // 

            pst.setString(1, txtcedula.getText());
            
            pst.setString(2, txtnombre.getText());

            pst.setString(3, txtapellido1.getText());
            pst.setString(4, txtapellido2.getText());
             pst.setString(5, txtemail.getText());
            pst.setInt(6, Integer.parseInt(txtbusqueda.getText()));
            pst.execute();

            JOptionPane.showMessageDialog(null, "Cliente Modificado");

            con.Desconectar();
            Limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Modificar cliente: " + e);
        }
        
    }//GEN-LAST:event_btneditarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        try {
            pst = con.conexion().prepareStatement("DELETE FROM registro_cliente  WHERE Id_Cliente=?");
            pst.setInt(1, Integer.parseInt(txtbusqueda.getText()));

            pst.execute();

            JOptionPane.showMessageDialog(null, "Cliente Eliminado");

            con.Desconectar();
            Limpiar();
        } catch (Exception e) {
            System.err.println("Error al eliminar el Cliente " + e);

        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        
        try {
            pst = con.conexion().prepareStatement("SELECT * FROM registro_cliente WHERE Id_Cliente=?");
            pst.setInt(1, Integer.parseInt(txtbusqueda.getText()));

            rs = pst.executeQuery();

            if (rs.next()) {
                txtcedula.setText(rs.getString("Cédula"));
                txtnombre.setText(rs.getString("Nombre"));
                txtapellido1.setText(rs.getString("PrimerApellido"));
                txtapellido2.setText(rs.getString("SegundoApellido"));
                txtemail.setText(rs.getString("CorreoElectronico"));
                
                con.Desconectar();
            } else {
                JOptionPane.showMessageDialog(null, "No existe un cliente con el nombre ingresado...");

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al Buscar Cliente: " + e);
        }
        
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtUsuarioVentas2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioVentas2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioVentas2ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void Limpiar(){
        txtcedula.setText("");
            txtnombre.setText("");
            txtapellido1.setText("");
            txtapellido2.setText("");
            txtemail.setText("");
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_AgregarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_AgregarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneditar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JTextField txtUsuarioVentas2;
    private javax.swing.JTextField txtapellido1;
    private javax.swing.JTextField txtapellido2;
    private javax.swing.JTextField txtbusqueda;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
